### ISSUE TITLE
API support

### ISSUE THREAD

**Issue by TuxCoding** [LapisPlugins/LapisLogin#1]
Do you have any kind of API for checking if the account exists, force register/login player and more?

**Comment by Dart2112** [comment]
I am looking at making an API if you could provide more detail on what you would like out of an API I will be happy to implement it. I'm starting it now so it should be ready to test within a few hours

**Comment by Dart2112** [comment]
so far I have a way to get the LapisLoginPlayer object with UUID and to check if a player is registered or logged in without having to get the object your self

**Comment by TuxCoding** [comment]
The following methods would be useful (maybe with throwing a documentation exception if something went wrong):
```java
boolean isRegistered(String)
void forceLogin(Player player)
void register(Player player, String password)
boolean isLoggedIn(Player)
void logout(Player)
void unregister(Player)
void unregister(String)
```

Then it would be great if you could add JavaDoc (including if the methods are thread-safe) documentation to those methods. Furthermore it's useful if it's an dedicated API class to invoke the methods on. It doesn't necessary need to be static. 

Events are nice too, but not required for me at the moment.

**Comment by Dart2112** [comment]
I won't be using player objects just because its setup to get info on offline players too, so it will be UUID based. events will be later but I can do an equivalent of each of those now. I don't have a place to host java docs but they will be added to the code and maybe a wiki on here. I reckon this won't take more than 15-30 minutes to set up.

**Comment by Dart2112** [comment]
![capture](https://user-images.githubusercontent.com/8944036/31220651-9c389bc6-aa08-11e7-86c2-0813256d06ad.PNG)
that's what I got so far, you will get that object with a UUID from the main API class

**Comment by TuxCoding** [comment]
>I won't be using player objects just because its setup to get info on offline players to

The methods with the Player objects should only be called when the player is online and therefore the (online) player object is present.

>I don't have a place to host java docs

Inside the code is enough. You could even use gh-pages (here on Github) for hosting it.

**Comment by Dart2112** [comment]
> The methods with the Player objects should only be called when the player is online and therefore the (online) player object is present.

I think its easier to use UUIDs since its what the rest of the plugin uses and it's not that had for you to get a UUID, I mean you can even do it in line with the getting of the API object if you want. 

Anyways where is a jar that has the API in it, I haven't done the java docs yet though. Just get an instance of the LapisLoginAPI class with your plugin class and call the LapisLoginAPIPlayer method with the UUID to get the player object.
[LapisLogin.zip](https://github.com/Dart2112/LapisLogin/files/1358790/LapisLogin.zip)

**Comment by Dart2112** [comment]
here is a version with JavaDocs, if it's all good then I'll push out an update
[LapisLogin.zip](https://github.com/Dart2112/LapisLogin/files/1358871/LapisLogin.zip)

**Comment by TuxCoding** [comment]
JavaDoc gets lost if generate a normal. You have to generate a special javadoc jar, but for me it's enough if I see it in the source code.

**Comment by Dart2112** [comment]
does maven have a setting for a JavaDocs jar, if so I'll do some googling

**Comment by TuxCoding** [comment]
Yes it does. There is javadoc plugin that generates the jar.

Example: https://github.com/dmulloy2/ProtocolLib/blob/master/modules/API/pom.xml#L124

**Comment by Dart2112** [comment]
[LapisLogin.zip](https://github.com/Dart2112/LapisLogin/files/1358902/LapisLogin.zip)
that has the main jar and JavaDoc jar

**Comment by TuxCoding** [comment]
Yes thanks.

**Comment by Dart2112** [comment]
version 1.0.2 with that API has been pushed out. I'll work on an event API. 

I'm thinking its gonna have
Login event
register event
logout event
password change/deregister event

**Comment by Dart2112** [comment]
https://dart2112.github.io/LapisLogin/
for the JavaDocs. I'll probably reopen this or contact you once I have the events ready to go

**Comment by TuxCoding** [comment]
BTW: You could use the gh-pages branch for Github hosting, then you don't need to deploy the auto generated documentation into the master branch.

**Comment by TuxCoding** [comment]
With a newer git version it's possible to use the `git worktree` command to even use a dedicated folder for a branch.

**Comment by Dart2112** [comment]
I just find it easier to just deal with one branch in Intelij and tell GitHub to use the docs folder.

**Comment by Dart2112** [comment]
Both player info and events have been added. Thanks very much for helping
