### ISSUE TITLE
Bug with certain items

### ISSUE THREAD

**Issue by Ziuru** [LapisPlugins/LapisLogin#2]
For some reason, even while logged in, certain items such as shields and more specifically the bow seem to be broken. If you try to shoot a bow, it will constantly attempt to draw the bow. you are only able to shoot the bow if you are looking at a block.

**Comment by Dart2112** [comment]
I'll look into this, should be an easy fix. Thanks for reporting it

**Comment by Dart2112** [comment]
[LapisLogin.zip](https://github.com/LapisPlugins/LapisLogin/files/1456552/LapisLogin.zip)
In the attached zip is a jar file that should fix the issue. if it does just let me know and I'll push out an update. if it doesn't then just give me a yell and I'll look into it more.

**Comment by Dart2112** [comment]
I have done some testing on my own server and the latest commit fixes the issues you described. I will push it out as an update in a minute.
