### ISSUE TITLE
Configurations

### ISSUE THREAD

**Issue by Resoluciones** [LapisPlugins/LapisLogin#3]
Great plugin!  But the configuration is resetting to its default.  Can you let me know?

Thanks!

**Comment by Dart2112** [comment]
I have fixed the issue in the code here on GitHub and will push out an update soon. until you get the update you can just change your config version to 4, it will replace it once more when you install the update

**Comment by Resoluciones** [comment]
great!! thanks for that more than fast fix!

**Comment by Dart2112** [comment]
I am currently in university so I will not be able to compile and upload the plugin for a few hours, but if you know how to use maven you can do it yourself or just set the config version to 4 and wait

**Comment by Resoluciones** [comment]
Sure it's OK I've already compiled it! And I will start to configure it! Thank you!
