### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by Resoluciones** [LapisPlugins/LapisLogin#4]
Plugin seems to be working great!

Can I ask you regarding the MySQL logs? shouldn't the IP number be registered? otherwise how can the plugin know when time is up to request login again, as per config set?

![image](https://user-images.githubusercontent.com/29935874/37318063-227ac6ea-2647-11e8-84ea-4c8743264ab0.png)

I ask you because the IP is blank in the MySQL.

Kindly let me know once possible.

Thanks!!!!

**Comment by Dart2112** [comment]
It should populate after the first login. It might be on the server and not pushed up to sql yet

**Comment by Resoluciones** [comment]
It's strange, I logged in and out several times and it's still blank.  But I will wait to another person with different IP to connect, to see if the IP is logged.  Maybe the problem is on my client or something different.

**Comment by Dart2112** [comment]
It might wait for your data to be cleared from memory. Weird that it didn't enter it when you registered.

**Comment by Resoluciones** [comment]
Hello Dart, I can confirm the IPs are not being stored for some reason:
![image](https://user-images.githubusercontent.com/29935874/37376335-83351dda-2702-11e8-8d07-e8dbe57ae28b.png)

**Comment by Dart2112** [comment]
The login times also aren't. I'll see what I can find but it looks like a piece of code isn't being run when the player logs in

**Comment by Resoluciones** [comment]
Ok thanks!

But is it working Ok for you in another server?

**Comment by Dart2112** [comment]
it seems to be working on my server. it seems odd that both the IP and the login time aren't working but the logout is. I just pushed another commit where I shuffled some things around. if it still doesn't work then the server must be doing something weird.

**Comment by Resoluciones** [comment]
Ok I'll compile and test it! Thanks!

**Comment by Resoluciones** [comment]
I've compiled it and it is doing the same (not logging IP and login times).

When I compile it I see some warnings: https://hasteb.in/ejufiveg.tex

I don't know if that warnings would be any problem or not.

In the console I don't see any errors.

Just in case:  Server version is: Paper version git-Paper-1349 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) and server is running in offline mode.

**Comment by Dart2112** [comment]
it shouldn't matter that its paper spigot but I'm gonna grab a copy of it and do some testing, those warnings are all not important and shouldn't make a difference.
