### ISSUE TITLE
Configurable Alert Message When Not Logged in

### ISSUE THREAD

**Issue by Resoluciones** [LapisPlugins/LapisLogin#5]
Would it be possible to add a configurable alert message for players that are not logged in?

Thanks!

**Comment by Dart2112** [comment]
Do you mean like repeating the current message about logging in?

**Comment by Resoluciones** [comment]
Yes that's right.  Currently there is no message alerting about that in my server.  Is it a bug in my server, or there should be one message requesting the player to log in in fact?

**Comment by Dart2112** [comment]
there is meant to be a message on join about logging in, Not sure why it's acting up. can you please send me a message (on spigot if you want) with your plugins and server version so I can test if it is just your server or a conflict with another plugin.
